### PR TITLE
Changed Menu width to 50% for small devices

### PR DESCRIPTION
**Pull request by labheshwar**

### CODE REVIEW

**Review by developer-junaid — CHANGES_REQUESTED** [review]
Thanks for your contribution. This change looks good but there's an issue with the Links that are in the Menu, they are wrapping !

Screenshot 2022-10-02 at 10 03 49 AM

**Comment by labheshwar** [comment]
> 

Looking into this.

**Review by developer-junaid — APPROVED** [review]
Very Nice, I'm merging it. Thanks

**Comment by developer-junaid** [comment]
Please resolve package.json conflict.

**Pull request merged**
