### PR TITLE
Added footer, socials, corrected some speling mistakes, and added som…

### PR DESCRIPTION
**Pull request by aishakhan0925**
…e texts

### CODE REVIEW

**Review by im-kamil — COMMENTED** [review]
A lightweight JavaScript library for creating particles. Particles.js is a plugin that I created for fun , for good looking websites

**Review by developer-junaid — CHANGES_REQUESTED** [review]
facing errors
Screenshot 2022-10-13 at 6 47 13 PM

Screenshot 2022-10-13 at 6 47 53 PM

**Comment by aishakhan0925** [comment]
Hey mate, I resolved these issues and added some more changes, please review.

**Comment by developer-junaid** [comment]
Sure checking in a while. Thanks

**Review by developer-junaid — APPROVED** [review]
Very well done. It's looking nicer

**Pull request merged**
